index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

orderBook:
    path: /available-books
    defaults: { _controller: 'App\Controller\DefaultController::getAvailableBooksAction' }

recentTrades:
    path: /trades
    defaults: { _controller: 'App\Controller\DefaultController::getRecentTrades' }

accountStatus:
    path: /account-status
    defaults: { _controller: 'App\Controller\DefaultController::getAccountStatus' }

balance:
    path: /balance
    defaults: { _controller: 'App\Controller\DefaultController::getBalance' }

fees:
    path: /fees
    defaults: { _controller: 'App\Controller\DefaultController::getFees' }

ledger:
    path: /ledger
    defaults: { _controller: 'App\Controller\DefaultController::getLedger' }

withdrawals:
    path: /withdrawals
    defaults: { _controller: 'App\Controller\DefaultController::getWithdrawals' }

fundings:
    path: /fundings
    defaults: { _controller: 'App\Controller\DefaultController::getFundings' }

orders:
    path: /orders
    defaults: { _controller: 'App\Controller\DefaultController::placeOrder' }